import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from './components/nav/Nav'
import Sidebar from './components/sidebar/Sidebar'
import { ReduxProvider } from './components/provider/reduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Certificaciones',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="es">
      <ReduxProvider>
        <body className={inter.className}>
          <Nav></Nav>
          <div className='grid grid-cols-8'>
            <Sidebar></Sidebar>
            <main className="flex min-h-screen flex-col items-center p-24 col-span-7">
              {children}
            </main>
          </div>
        </body>
      </ReduxProvider>
    </html >
  )
}

export default RootLayout